seed: 42
gpus:
  num_gpus: -1
paths:
  data_path: /home/ranjith/data
  meta_path: /home/ranjith/d4ai/ranjith_projects/interior_classification/meta_data
  cars_train_path: /home/ranjith/d4ai/ranjith_projects/interior_classification/meta_data/train_sampled.csv
  cars_val_path: /home/ranjith/d4ai/ranjith_projects/interior_classification/meta_data/val.csv
  cars_test_path: /home/ranjith/d4ai/ranjith_projects/interior_classification/meta_data/test.csv
  models_dir: /home/ranjith/d4ai/ranjith_projects/interior_classification/models/PartiallyCorrected

optimizer_params:
  optimizer: AdamW
  learning_rate: 5.0e-05
  momentum: 0.9
  weight_decay: 1.0e-02
  beta1: 0.9
  beta2: 0.999
scheduler_params:
  scheduler: ReduceLROnPlateau
  tmax: 30
  eta_min: 5.0e-06
  metric: val_loss
  mode: min
  factor: 0.95
  patience: 2
train:
  num_gpus: -1
  batch_size: 16
  num_workers: 1
  grad_clip: 0.1
  epochs: 30
  start_iter: 0
  early_stop_threshold: 0.001
  checkpoint_period: 5
  metric_threshold: 0.95
  es_monitor: val_acc
  es_mode: max
  es_patience: 2
  es_verbose: true

data_transforms:
  image_size: 300
  test_image_size: 384
  image_channels: 3
  means:
    - 0.485
    - 0.456
    - 0.406
  stds:
    - 0.229
    - 0.224
    - 0.225
  scale: 1.1
  auto_augment: rand-m7-n4-mstd0.5-inc1
